
DROP DATABASE if exists irb2014; 


CREATE DATABASE irb2014;
use irb2014;

CREATE TABLE Tournament
(
T_ID INT PRIMARY KEY auto_increment,
T_Name VARCHAR(5) NOT NULL,
T_Date DATE NOT NULL
);

CREATE TABLE Team
(
Team_ID INT PRIMARY KEY,
Team_Name VARCHAR(20) NOT NULL
);

CREATE TABLE Game
(
Game_ID INT PRIMARY KEY auto_increment,
T_ID INT NOT NULL,
FOREIGN KEY (T_ID) REFERENCES Tournament(T_ID),
Team_1 INT NOT NULL,
FOREIGN KEY (Team_1) REFERENCES Team(Team_ID),
Team_2 INT NOT NULL,
FOREIGN KEY (Team_2) REFERENCES Team(Team_ID),
T_Game_Number INT NOT NULL,
Game_Time TIME NOT NULL,
Score_1 INT NOT NULL,
Score_2 INT NOT NULL,
Winner VARCHAR(25),
CHECK (Team_1 <> Team_2)
);

CREATE TABLE Possession
(
Poss_ID INT PRIMARY KEY auto_increment,
Team_ID INT NOT NULL,
FOREIGN KEY (Team_ID) REFERENCES Team(Team_ID),
Game_ID INT NOT NULL,
FOREIGN KEY (Game_ID) REFERENCES Game(Game_ID),
T_Name VARCHAR(10) NOT NULL,
Origin VARCHAR(40) NOT NULL,
Start_ INT NOT NULL,
End_ INT NOT NULL,
Lost VARCHAR(40) NOT NULL
);

CREATE TABLE Team_Tournament
(
Team_ID INT,
T_ID INT,
PRIMARY KEY (Team_ID, T_ID),
FOREIGN KEY (Team_ID) REFERENCES Team(Team_ID),
FOREIGN KEY (T_ID) REFERENCES Tournament(T_ID)
);
